INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (1, N'Astronomi')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (2, N'Çocuk Etkinlikleri')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (3, N'Dış Ticaret')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (4, N'Dinler ve İnançlar')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (5, N'Dijital Pazarlama')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (6, N'Ekonomi')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (7, N'Eğitim')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (8, N'E-Spor')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (9, N'E-ticaret')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (10, N'FinTech')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (11, N'Girişimcilik')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (12, N'Kariyer')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (13, N'Kişisel Gelişim')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (14, N'Kriptopara')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (15, N'Moda')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (16, N'Mühendislik')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (17, N'Müzik')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (18, N'Özel ders')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (19, N'Psikoloji')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (20, N'Sağlık')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (21, N'Sanat')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (22, N'Siyaset')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (23, N'Sosyal Medya')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (24, N'Spor')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (25, N'Teknoloji')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (26, N'Ücretsiz Etkinlikler')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (27, N'Yabancı Dil')